language: node_js
node_js:
  - "node"

install:
  - npm update

before_script:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"

script:
  - npm run deploy